# Google Cloud Build Configuration for Panelin API
# =================================================
# This config builds, tests, and deploys the Panelin API to Cloud Run
# 
# Trigger this build manually or set up a GitHub trigger:
# gcloud builds submit --config cloudbuild.yaml

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest'
      - '-f'
      - 'Copia de panelin_agent_v2/Dockerfile'
      - 'Copia de panelin_agent_v2'

  # Step 2: Run tests (optional - comment out if no tests configured)
  - name: 'python:3.11-slim'
    id: 'run-tests'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd "Copia de panelin_agent_v2" && \
        pip install -q -r requirements.txt && \
        pytest -q tests/ || echo "Tests skipped or not configured"
    waitFor: ['-']  # Run in parallel with image build

  # Step 3: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}'
    waitFor: ['build-image', 'run-tests']

  # Step 4: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest'
    waitFor: ['push-image']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloudrun'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
      # Choose authentication mode (uncomment one):
      - '--allow-unauthenticated'  # For public access
      # - '--no-allow-unauthenticated'  # For IAM-authenticated access only
    waitFor: ['push-latest']

# Substitution variables with defaults
substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api
  _SERVICE_ACCOUNT: panelin-runner@${PROJECT_ID}.iam.gserviceaccount.com
  _MEMORY: 512Mi
  _CPU: '1'
  _TIMEOUT: '300'
  _CONCURRENCY: '80'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Build timeout
timeout: '1200s'  # 20 minutes
