steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - .
  - name: "python:3.11-slim"
    entrypoint: sh
    args:
      - -c
      - |
        pip install -r "Copia de panelin_agent_v2/requirements.txt"
        pytest -q "Copia de panelin_agent_v2/tests"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:$COMMIT_SHA"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --no-allow-unauthenticated
      - --service-account
      - "panelin-runner@${_PROJECT_ID}.iam.gserviceaccount.com"
      - --memory
      - "512Mi"
      - --cpu
      - "1"
      - --timeout
      - "300"
      - --concurrency
      - "80"
      - --min-instances
      - "0"
      - --max-instances
      - "10"
      - --set-secrets
      - "OPENAI_API_KEY=projects/${_PROJECT_ID}/secrets/OPENAI_API_KEY:latest"
substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api
options:
  logging: CLOUD_LOGGING_ONLY
