steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'Copia de panelin_agent_v2'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      # Security: Allow unauthenticated for public API. 
      # Remove or change to --no-allow-unauthenticated for internal services.
      - '--allow-unauthenticated'
      # Resources & Limits
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      # Autoscaling
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      # Health Checks (Cloud Run automatically uses the PORT, but we can be explicit if needed)
      # Note: Liveness/Readiness probes are configured in the service YAML or via beta flags in gcloud.
      # Basic startup probe is automatic on the listening port.

substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api
