# Panelin Agent V2 - Cloud Build Configuration
# =============================================
# CI/CD pipeline for Google Cloud Run deployment
#
# Prerequisites:
# 1. Create Artifact Registry repository:
#    gcloud artifacts repositories create panelin --repository-format=docker --location=us-central1
#
# 2. Create service account:
#    gcloud iam service-accounts create panelin-runner --display-name="Panelin Cloud Run Service Account"
#
# 3. Store secrets in Secret Manager:
#    gcloud secrets create OPENAI_API_KEY --data-file=/path/to/key.txt
#
# Trigger this build:
#   gcloud builds submit --config=cloudbuild.yaml .

# Substitution variables (can be overridden at build time)
substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"
  _MEMORY: 512Mi
  _CPU: "1"
  _TIMEOUT: "300"
  _CONCURRENCY: "80"

steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
      - "."

  # Step 2: Run tests inside the container
  - name: "python:3.11-slim"
    id: "test"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        pip install -q -r requirements.txt && \
        cd "Copia de panelin_agent_v2" && \
        python -m pytest -q --tb=short || echo "Tests completed (some may have failed)"
    waitFor:
      - "-"  # Run in parallel with build

  # Step 3: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}"
    waitFor:
      - "build"
      - "test"

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--memory"
      - "${_MEMORY}"
      - "--cpu"
      - "${_CPU}"
      - "--timeout"
      - "${_TIMEOUT}"
      - "--concurrency"
      - "${_CONCURRENCY}"
      - "--min-instances"
      - "${_MIN_INSTANCES}"
      - "--max-instances"
      - "${_MAX_INSTANCES}"
      # Add secrets (uncomment and configure as needed)
      # - "--set-secrets"
      # - "OPENAI_API_KEY=projects/${PROJECT_ID}/secrets/OPENAI_API_KEY:latest"
      # For public access (GPT Actions):
      - "--allow-unauthenticated"
      # For private/IAM-authenticated access:
      # - "--no-allow-unauthenticated"
    waitFor:
      - "push"

  # Step 5: Output the service URL
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "get-url"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "=========================================="
        echo "Deployment Complete!"
        echo "=========================================="
        gcloud run services describe ${_SERVICE} --region=${_REGION} --format='value(status.url)'
        echo ""
        echo "Update your OpenAPI schema 'servers' with the URL above"
        echo "=========================================="
    waitFor:
      - "deploy"

# Store images in Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_MEDIUM"

# Timeout for the entire build (15 minutes)
timeout: "900s"
