steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
      - "-f"
      - "Copia de panelin_agent_v2/Dockerfile"
      - "Copia de panelin_agent_v2"

  # Step 2: Run tests (optional but recommended)
  - name: "python:3.11-slim"
    entrypoint: sh
    dir: "Copia de panelin_agent_v2"
    args:
      - "-c"
      - |
        pip install -r requirements.txt && \
        pytest -q tests/ || echo "Tests skipped or failed - review before production deployment"

  # Step 3: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:$COMMIT_SHA"

  # Step 4: Push the latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"

  # Step 5: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "300"
      - "--concurrency"
      - "80"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      # Uncomment the appropriate authentication option:
      # For public API (no authentication required):
      - "--allow-unauthenticated"
      # For IAM-authenticated API:
      # - "--no-allow-unauthenticated"
      # Set secrets from Secret Manager (uncomment and configure as needed):
      # - "--set-secrets"
      # - "OPENAI_API_KEY=OPENAI_API_KEY:latest,SHOPIFY_API_KEY=SHOPIFY_API_KEY:latest"
      # Set service account (uncomment and configure):
      # - "--service-account"
      # - "panelin-runner@${PROJECT_ID}.iam.gserviceaccount.com"

# Substitution variables (customize these for your project)
substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api

# Optional: Set build timeout (default is 10 minutes)
timeout: 1200s

# Optional: Specify machine type for faster builds
options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

# Images to be pushed to registry
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:$COMMIT_SHA"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
