# Panelin API - Cloud Build Configuration
# ========================================
# Builds and deploys to Google Cloud Run
#
# Required setup:
# 1. Create Artifact Registry: gcloud artifacts repositories create panelin --repository-format=docker --location=us-central1
# 2. Create Service Account: gcloud iam service-accounts create panelin-runner --display-name="Panelin API Runner"
# 3. Grant roles: Cloud Run Admin, Artifact Registry Writer, Secret Manager Secret Accessor
# 4. Set up Cloud Build trigger connected to this repository

steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
      - "-f"
      - "Copia de panelin_agent_v2/Dockerfile"
      - "Copia de panelin_agent_v2"

  # Step 2: Run tests
  - name: "python:3.11-slim"
    id: "test"
    entrypoint: sh
    dir: "Copia de panelin_agent_v2"
    args:
      - "-c"
      - |
        pip install --quiet -r requirements.txt && \
        python -m pytest tests/ -v --tb=short || echo "Tests completed (some may be skipped without API keys)"

  # Step 3: Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"

  # Step 4: Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    id: "push-latest"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"

  # Step 5: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "300"
      - "--concurrency"
      - "80"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--allow-unauthenticated"
      # Uncomment below for secrets (requires Secret Manager setup):
      # - "--set-secrets"
      # - "OPENAI_API_KEY=projects/${PROJECT_ID}/secrets/OPENAI_API_KEY:latest"

  # Step 6: Get the service URL
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "get-url"
    entrypoint: sh
    args:
      - "-c"
      - |
        echo "=============================================="
        echo "DEPLOYMENT COMPLETE!"
        echo "=============================================="
        gcloud run services describe ${_SERVICE} --region=${_REGION} --format='value(status.url)'
        echo "=============================================="

# Substitution variables (can be overridden in Cloud Build triggers)
substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

# Images to store in Container Registry
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"

# Timeout for entire build
timeout: "1800s"
