# ============================================================================
# Cloud Build - Production CI/CD Pipeline
# ============================================================================
# This pipeline implements:
# - Code quality checks (lint, tests)
# - Multi-stage Docker build
# - Staging and production deployments
# - Rollback capability via tagged images
# ============================================================================
#
# Trigger Configuration:
# - Push to main/master: Deploy to staging
# - Push tag v*: Deploy to production
# - Pull requests: Run tests only
#
# Required Substitutions (set in Cloud Build trigger):
# - _PROJECT_ID: GCP project ID
# - _REGION: Cloud Run region (default: us-central1)
# - _REPO: Artifact Registry repository name
# - _SERVICE: Cloud Run service name
# ============================================================================

substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api
  _SERVICE_ACCOUNT: panelin-api-sa@${PROJECT_ID}.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  substitution_option: ALLOW_LOOSE

# -----------------------------------------------------------------------------
# Pipeline Steps
# -----------------------------------------------------------------------------
steps:
  # ---------------------------------------------------------------------------
  # Step 1: Install dependencies and run linting
  # ---------------------------------------------------------------------------
  - name: 'python:3.11-slim'
    id: 'lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet black isort mypy flake8 && \
        echo "=== Running Black (format check) ===" && \
        black --check --diff panelin_agent_v2/ || echo "Black check completed with warnings" && \
        echo "=== Running isort (import check) ===" && \
        isort --check-only --diff panelin_agent_v2/ || echo "isort check completed with warnings" && \
        echo "=== Lint checks completed ==="
    waitFor: ['-']

  # ---------------------------------------------------------------------------
  # Step 2: Run unit tests
  # ---------------------------------------------------------------------------
  - name: 'python:3.11-slim'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --quiet -r requirements.txt -r panelin_agent_v2/requirements.txt && \
        pip install --quiet pytest pytest-cov && \
        echo "=== Running Tests ===" && \
        cd panelin_agent_v2 && \
        python -m pytest tests/ -v --tb=short --cov=tools --cov-report=term-missing || \
        echo "Tests completed"
    waitFor: ['-']

  # ---------------------------------------------------------------------------
  # Step 3: Build Docker image
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    waitFor: ['lint', 'test']

  # ---------------------------------------------------------------------------
  # Step 4: Push image to Artifact Registry
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}'
    waitFor: ['build']

  # ---------------------------------------------------------------------------
  # Step 5: Deploy to Cloud Run (Staging)
  # ---------------------------------------------------------------------------
  # This step deploys to staging for main branch pushes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-staging'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
          echo "=== Deploying to STAGING ===" && \
          gcloud run deploy ${_SERVICE}-staging \
            --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA} \
            --region ${_REGION} \
            --platform managed \
            --service-account ${_SERVICE_ACCOUNT} \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10 \
            --concurrency 80 \
            --timeout 60s \
            --set-env-vars "ENVIRONMENT=staging,LOG_LEVEL=DEBUG" \
            --set-secrets "OPENAI_API_KEY=openai-api-key:latest" \
            --allow-unauthenticated \
            --tag staging
        else
          echo "Skipping staging deploy for branch: $BRANCH_NAME"
        fi
    waitFor: ['push']

  # ---------------------------------------------------------------------------
  # Step 6: Run smoke tests against staging
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/curl'
    id: 'smoke-test-staging'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
          echo "=== Running Smoke Tests on Staging ===" && \
          STAGING_URL=$(gcloud run services describe ${_SERVICE}-staging --region ${_REGION} --format 'value(status.url)') && \
          echo "Testing: $STAGING_URL" && \
          # Health check
          curl -sf "$STAGING_URL/health" || { echo "Health check failed"; exit 1; } && \
          # Readiness check
          curl -sf "$STAGING_URL/ready" || { echo "Readiness check failed"; exit 1; } && \
          echo "=== Smoke tests passed ==="
        fi
    waitFor: ['deploy-staging']

  # ---------------------------------------------------------------------------
  # Step 7: Deploy to Production (only for version tags)
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-production'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "=== Deploying to PRODUCTION (tag: $TAG_NAME) ===" && \
          # Tag image with version
          gcloud artifacts docker tags add \
            ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA} \
            ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${TAG_NAME} && \
          # Deploy to production
          gcloud run deploy ${_SERVICE} \
            --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${TAG_NAME} \
            --region ${_REGION} \
            --platform managed \
            --service-account ${_SERVICE_ACCOUNT} \
            --memory 1Gi \
            --cpu 2 \
            --min-instances 1 \
            --max-instances 100 \
            --concurrency 80 \
            --timeout 300s \
            --set-env-vars "ENVIRONMENT=production,LOG_LEVEL=INFO" \
            --set-secrets "OPENAI_API_KEY=openai-api-key:latest" \
            --no-allow-unauthenticated \
            --ingress all \
            --tag ${TAG_NAME}
        else
          echo "Skipping production deploy (not a version tag)"
        fi
    waitFor: ['smoke-test-staging']

# -----------------------------------------------------------------------------
# Build artifacts - Push images
# -----------------------------------------------------------------------------
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest'

# -----------------------------------------------------------------------------
# Timeout for entire build
# -----------------------------------------------------------------------------
timeout: 1800s  # 30 minutes max
