#!/usr/bin/env python3
"""
Report Distributor
==================

Distributes generated reports via email, file sharing, or other channels.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import Dict, List, Optional, Any
from pathlib import Path
from datetime import datetime


class ReportDistributor:
    """Distributes reports to stakeholders"""
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize report distributor
        
        Args:
            config: Email configuration with smtp_server, smtp_port, username, password, recipients
        """
        self.config = config or {}
        self.distribution_log: List[Dict[str, Any]] = []
    
    def distribute_report(
        self,
        filepath: str,
        report_type: str,
        recipients: Optional[List[str]] = None
    ):
        """
        Distribute a report
        
        Args:
            filepath: Path to report file
            report_type: Type of report
            recipients: Email recipients (overrides config)
        """
        if not Path(filepath).exists():
            raise FileNotFoundError(f"Report file not found: {filepath}")
        
        recipients = recipients or self.config.get("recipients", [])
        
        if not recipients:
            # No recipients configured, just log
            self.distribution_log.append({
                "timestamp": datetime.now().isoformat(),
                "filepath": filepath,
                "report_type": report_type,
                "method": "file_only",
                "status": "completed"
            })
            return
        
        # Email distribution
        try:
            self._send_email(filepath, report_type, recipients)
            
            self.distribution_log.append({
                "timestamp": datetime.now().isoformat(),
                "filepath": filepath,
                "report_type": report_type,
                "method": "email",
                "recipients": recipients,
                "status": "completed"
            })
        
        except Exception as e:
            self.distribution_log.append({
                "timestamp": datetime.now().isoformat(),
                "filepath": filepath,
                "report_type": report_type,
                "method": "email",
                "recipients": recipients,
                "status": "failed",
                "error": str(e)
            })
            raise
    
    def _send_email(
        self,
        filepath: str,
        report_type: str,
        recipients: List[str]
    ):
        """Send report via email"""
        if not self.config.get("smtp_server"):
            raise ValueError("Email not configured (missing smtp_server)")
        
        # Create message
        msg = MIMEMultipart()
        msg['From'] = self.config.get("from_email", "reports@panelin.local")
        msg['To'] = ", ".join(recipients)
        msg['Subject'] = f"Panelin {report_type} Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Email body
        body = f"""
        Automated report generated by Panelin system.
        
        Report Type: {report_type}
        Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        
        Please see attached report file.
        """
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach report file
        with open(filepath, 'rb') as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename={Path(filepath).name}'
            )
            msg.attach(part)
        
        # Send email
        with smtplib.SMTP(self.config['smtp_server'], self.config.get('smtp_port', 587)) as server:
            server.starttls()
            if self.config.get('username') and self.config.get('password'):
                server.login(self.config['username'], self.config['password'])
            server.send_message(msg)
    
    def get_distribution_log(self, limit: int = 50) -> List[Dict[str, Any]]:
        """Get recent distribution log entries"""
        return self.distribution_log[-limit:]
