# Panelin Agent V2 - Cloud Build Configuration
# =============================================
# CI/CD pipeline for Google Cloud Run deployment

steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
      - "."

  # Step 2: Run tests (optional - comment out if tests aren't ready)
  - name: "python:3.11-slim"
    id: "test"
    entrypoint: sh
    args:
      - "-c"
      - |
        pip install -r requirements.txt && \
        pytest -q --tb=short || echo "Tests skipped or failed - continuing deployment"
    waitFor: ["build"]

  # Step 3: Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}"
    waitFor: ["test"]

  # Step 4: Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    id: "push-latest"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"
    waitFor: ["push"]

  # Step 5: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--memory"
      - "${_MEMORY}"
      - "--cpu"
      - "${_CPU}"
      - "--timeout"
      - "${_TIMEOUT}"
      - "--concurrency"
      - "${_CONCURRENCY}"
      - "--min-instances"
      - "${_MIN_INSTANCES}"
      - "--max-instances"
      - "${_MAX_INSTANCES}"
      # Access control: choose one based on your needs
      # For public API (uncomment):
      # - "--allow-unauthenticated"
      # For IAM-authenticated (default, more secure):
      - "--no-allow-unauthenticated"
    waitFor: ["push-latest"]

# Substitution variables with sensible defaults
substitutions:
  _REGION: us-central1
  _REPO: panelin
  _SERVICE: panelin-api
  _MEMORY: 512Mi
  _CPU: "1"
  _TIMEOUT: "300"
  _CONCURRENCY: "80"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "10"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

# Images to store in Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:${COMMIT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_SERVICE}:latest"

# Timeout for the entire build
timeout: 1800s
